### ISSUE TITLE
Error when using Cucumber Living plugin from Jenkins

### ISSUE THREAD

**Issue by clausfod** [rmpestano/cukedoctor#102]
Hi,

I guess this when using the Cucumber Living plugin on Jenkins (latest one):

`com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: java.io.InputStreamReader@f7d9398; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:327)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at com.github.cukedoctor.parser.FeatureParser.parse(FeatureParser.java:31)
	at com.github.cukedoctor.parser.FeatureParser.parse(FeatureParser.java:68)
	at com.github.cukedoctor.parser.FeatureParser.findAndParse(FeatureParser.java:101)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.perform(CukedoctorPublisher.java:157)`

We get this a lot on the log files...

Any idea whats going on ?

**Comment by rmpestano** [comment]
Hi @clausfod, this is an error or a warning with stacktrace?

can you share the cucumber json output?

**Comment by clausfod** [comment]
Investigated it a little further... I think it's an error in the Cucumber living plugin...

`Could not map json file:/usr/data/jenkins/jobs/JAVA_EE/jobs/rs-mortgage-agreement/jobs/rs-mortgage-agreement feature/branches/feature-N.ai2en1cos1cl.le-status/builds/7/rs-mortgage-agreement-services/target/api/swagger.json`

Somehow the plugin tries to fetch a swagger.json from the Jenkins master instead of the slave running the job. I will investigate further

**Comment by rmpestano** [comment]
Hi, I think It is Just a warning, [see here](https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-converter/src/main/java/com/github/cukedoctor/parser/FeatureParser.java#L48)

Is It preventing the documentation to be generated?

**Comment by clausfod** [comment]
Hi,
It just a warning the documentation is generated. Just close the issue. Thanks for helping out :+1:
