### ISSUE TITLE
maven plugin build failures in jenkins pipeline

### ISSUE THREAD

**Issue by scaliest-ripped** [rmpestano/cukedoctor#124]
I'm using cukedoctor in a maven project. I've added cukedoctor-converter (r1.2.1) as a dependency with the 'test' scope.

I've also added cukedoctor-maven-plugin (r1.2.1) and configured it according to the Readme, so that it runs during the verify phase. 

Running _mvn clean install_ generates the documentation as would be expected locally. However, when pushing to our pipeline app the following error breaks the build:
`
Caused by: java.lang.NoClassDefFoundError: com/github/cukedoctor/api/DocumentAttributes
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
....
`

Further down the stacktrace we get this:

`
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing com.github.cukedoctor:cukedoctor-maven-plugin:1.2.1:execute: com/github/cukedoctor/api/DocumentAttributes
`

This seems to be a result of an import statement which looks for com.github.cukedoctor.api.Document.attributes, which it cannot find, which is just as well because it does not exist in the source code or locally in my .m2 directory.

There does not appear to be any documentation available for troubleshooting this issue. If there is another way we can get the documentation to generate any time a developer builds we'd be open to hearing about it. 

Oddly, this error only manifests occasionally when we commit to a remote branch, but always fails when we merge to master. 

Any advice?

**Comment by scaliest-ripped** [comment]
Forgot to ask: are there any other dependencies or libraries we might have forgotten to include that would cause this?

**Comment by scaliest-ripped** [comment]
It seems there is a 'Jenkins Pipeline Plugin' for cukedoctor. I'm assuming we need to install this to get this to work, although it's odd that our build sometimes works without it. I'm going to close the issue as this seems to be the likely culprit.
