### ISSUE TITLE
Class not found: com.github.cukedoctor.config.GlobalConfig in Jenkins Plugin v3.2

### ISSUE THREAD

**Issue by it-bas** [rmpestano/cukedoctor#188]
I get an error in my Jenkins Job and I don't find any hint what the problem is.

Jenkins 2.263.4
Living Documentation 3.2

config:
```
stage('Test image') {
            steps {
                withMaven(maven: 'Maven 3.6.0') {
                    sh "mvn test"
                }
                livingDocs(title: 'Akzeptanztest-Dokumentation')
            }
        }
```

```
hudson.remoting.ProxyException: org.yaml.snakeyaml.error.YAMLException: Class not found: com.github.cukedoctor.config.GlobalConfig
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:664)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:322)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
Caused: hudson.remoting.ProxyException: Can't construct a java object for tag:yaml.org,2002:com.github.cukedoctor.config.GlobalConfig; exception=Class not found: com.github.cukedoctor.config.GlobalConfig
 in 'reader', line 1, column 1:
    layoutConfig:
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:335)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at com.github.cukedoctor.config.GlobalConfig.createInstance(GlobalConfig.java:51)
	at com.github.cukedoctor.config.GlobalConfig.getInstance(GlobalConfig.java:29)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.perform(CukedoctorPublisher.java:170)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at  org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rmpestano** [comment]
Hi @it-bas, unfortunately, Jenkins and Asciidoc/Cukedoctor integration is not easy (see #157). I'll deprecate Jenkins plugin as it is not a suitable platform to publish the documentation. The replacement will be the Antora integration.
