### ISSUE TITLE
UnrecognizedPropertyException: Unrecognized field "comments"

### ISSUE THREAD

**Issue by tfnico** [rmpestano/cukedoctor#67]
I discovered this through [using the Jenkins Living Documentation plugin](https://github.com/jenkinsci/cucumber-living-documentation-plugin/issues/2). The problem is that my cucumber specs contain comments that end up in the json like this:

```
....
"type": "scenario",
"keyword": "Scenario",
"steps": [
  {
	"result": {
	  "duration": 1311092270,
	  "status": "passed"
	},
	"line": 8,
	"name": "I am logged in",
	"match": {
	  "location": "LoginStepDefs.iLogIn()"
	},
	"keyword": "Given "
  },
  {
	"result": {
	  "duration": 550836602,
	  "status": "passed"
	},
	"line": 9,
	"name": "I enter a submission with the following parameters:",
	"match": {
	  "location": "SubmissionStepDefs.iEnterASubmissionWithTheFollowingParameters(String,String\u003e)"
	},
	"rows": [
	  {
		"comments": [
		  {
			"line": 10,
			"value": "# Note that a random suffix will be added!"
		  }
		],
		"cells": [
		  "ID",
		  "AHKTK7BGXX"
		],
		"line": 11
	  },
	  {
		"cells": [
		  "Length",
		  "3"
		],
		"line": 12
	  }
	],
	"keyword": "And "
  },
  .....
```
That comment will make cukedoctor fail. I've recreated the problem with the more recent [cukedoctor development snapshot from here](https://github.com/rmpestano/cukedoctor/issues/66#issuecomment-234138483):

```
java -jar ~/Downloads/cukedoctor-main-1.0.3-20160721.021327-8.jar -p build/cucumber-results -o build/cucumber-results/cukedoctor -f all -t "Feature Tests" -toc left
Generating living documentation with args:
-f: all
-p: build/cucumber-results
-t: Feature Tests
-o: build/cucumber-results/cukedoctor
Jul 29, 2016 11:23:06 AM com.github.cukedoctor.parser.FeatureParser parse
WARNING: Could not map json file:/Users/tfnico/projects/foo/build/cucumber-results/e2e.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "comments" (class com.github.cukedoctor.api.model.Row), not marked as ignorable (one known property: "cells"])
 at [Source: java.io.InputStreamReader@271053e1; line: 758, column: 30] (through reference chain: java.util.ArrayList[4]->com.github.cukedoctor.api.model.Feature["elements"]->java.util.ArrayList[0]->com.github.cukedoctor.api.model.Scenario["steps"]->java.util.ArrayList[1]->com.github.cukedoctor.api.model.Step["rows"]->Object[][0]->com.github.cukedoctor.api.model.Row["comments"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:855)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1083)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1389)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1367)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:266)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
        at com.github.cukedoctor.parser.FeatureParser.parse(FeatureParser.java:31)
        at com.github.cukedoctor.parser.FeatureParser.parse(FeatureParser.java:68)
        at com.github.cukedoctor.CukedoctorMain.execute(CukedoctorMain.java:105)
        at com.github.cukedoctor.CukedoctorMain.main(CukedoctorMain.java:149)

No features found in path:build/cucumber-results

```

**Comment by rmpestano** [comment]
Hi @tfnico, thanks for diving into this issue.

Cukedoctor is not expecting the 'comments' attribute as you [can see here](https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-converter/src/main/java/com/github/cukedoctor/api/model/Row.java#L5).

An easy solution is to add it to ignored properties and then it will not appear in living docs. If you have no problems with it I can fix it and push a new version (also for the jenkins plugin).

Or we can discuss how these comments should be rendered in the living documentation.

**Comment by tfnico** [comment]
@rmpestano Thanks for the quick reply! Sure, I have no problems leaving out the comments. They are considered a code smell in Cucumber tests anyway.
