### ISSUE TITLE
mvn Cukedoctor:execute is failing

### ISSUE THREAD

**Issue by vikramvi** [rmpestano/cukedoctor#82]
As per section 7.1 I tried to use maven plugin but it's failing with error

mvn Cukedoctor:execute
[INFO] Scanning for projects...
[WARNING] The POM for com.github.cukedoctor:Cukedoctor-maven-plugin:jar:1.0.6 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.github.cukedoctor:Cukedoctor-maven-plugin:1.0.6: Plugin com.github.cukedoctor:Cukedoctor-maven-plugin:1.0.6 or one of its dependencies could not be resolved: Failure to find com.github.cukedoctor:Cukedoctor-maven-plugin:jar:1.0.6 in http://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading: http://jcenter.bintray.com/org/codehaus/mojo/maven-metadata.xml
Downloading: http://jcenter.bintray.com/org/apache/maven/plugins/maven-metadata.xml
Downloaded: http://jcenter.bintray.com/org/apache/maven/plugins/maven-metadata.xml (18 KB at 54.5 KB/sec)
Downloaded: http://jcenter.bintray.com/org/codehaus/mojo/maven-metadata.xml (27 KB at 81.2 KB/sec)

You can use my project https://github.com/vikramvi/AppiumSerenityPOC to reproduce this issue.

@Test
    public void shouldSaveDocumentationIntoDisk()

with this approach first I got living_documentation.adoc and now want to convert to html format with mvn command per section 7.1

please clarify

**Comment by rmpestano** [comment]
Hi,

Three things:

1 - there is a typo in readme (due to a refactory), the right command is **cukedoctor:execute** (without capital letter)

2 - the command will scan (recursively) .json files generated by your cucumber tests so make sure that those files exists when you run the command

3 - You need cukedoctor-maven-plugin in your pom.xml, again there is a typo in readme, the right dependency is:

```
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>1.0.6</version>
</plugin>
```

**Comment by vikramvi** [comment]
@rmpestano Thanks for reply, I did changes as suggested but still getting error as below

mvn cukedoctor:execute
[INFO] Scanning for projects...
[WARNING] The POM for com.github.cukedoctor:cukedoctor-maven-plugin:jar:1.0.6 is missing, no dependency information available
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Test project with Serenity and Appium to perform UI tests on native mobile app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- cukedoctor-maven-plugin:1.0.6:execute (default-cli) @ serenity-appium-mobile-native-app-automation ---
[WARNING] The POM for com.github.cukedoctor:cukedoctor-maven-plugin:jar:1.0.6 is missing, no dependency information available
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (165 KB at 327.3 KB/sec)
[WARNING] Error injecting: com.github.cukedoctor.mojo.CukedoctorMojo
java.lang.NoClassDefFoundError: com/github/cukedoctor/api/DocumentAttributes
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:613)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:569)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:555)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.github.cukedoctor.api.DocumentAttributes
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 58 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.917 s
[INFO] Finished at: 2016-11-24T14:50:20+01:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.cukedoctor:cukedoctor-maven-plugin:1.0.6:execute (default-cli) on project serenity-appium-mobile-native-app-automation: Execution default-cli of goal com.github.cukedoctor:cukedoctor-maven-plugin:1.0.6:execute failed: A required class was missing while executing com.github.cukedoctor:cukedoctor-maven-plugin:1.0.6:execute: com/github/cukedoctor/api/DocumentAttributes
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.cukedoctor:cukedoctor-maven-plugin:1.0.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/vikram-anna/.m2/repository/com/github/cukedoctor/cukedoctor-maven-plugin/1.0.6/cukedoctor-maven-plugin-1.0.6.jar
[ERROR] urls[1] = file:/Users/vikram-anna/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.github.cukedoctor.api.DocumentAttributes
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by rmpestano** [comment]
Strange, you are failing to download the plugin from maven central but it is available there,see here:http://search.maven.org/#search%7Cga%7C1%7Ccukedoctor-maven-plugin

Can you try to run the maven command with **-U** flag?

**Comment by rmpestano** [comment]
Or maybe try to upgrade your maven installation to 3.1.x

**Comment by vikramvi** [comment]
yahooooo..

mvn -U cukedoctor:execute    did the trick (  Apache Maven 3.3.9 )

It will be nice if I can pass parameter where to look for json files 

<inputDir>cucumber-json-dir</inputDir>

As there are some unrelated json files get created as part of automation script; which are not needed by cukedoctor.

Please review.

**Comment by rmpestano** [comment]
you can try to set **featuresDir** parameter, ex:

```
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>1.0.6</version>
         <configuration>
             <featuresDir>/target/cucumber-output</featuresDir>
         </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>execute</goal>
                </goals>
                <phase>verify</phase>
            </execution>
        </executions>
</plugin>
```

I'll add it to readme as its undocumented.

**Comment by vikramvi** [comment]
small correction, it should be as below

<featuresDir>target/cucumber_json</featuresDir>

Thanks for quick solution

**Comment by rmpestano** [comment]
Hi @vikramvi, can we close this one?
